In [1]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,34,5])

In [4]:
arr

array([ 1,  2, 34,  5])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [14]:
 myarr=np.array([[1,2,3],[2,3,4],[5,6,7],[4,6,4]])

In [15]:
myarr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7],
       [4, 6, 4]])

In [16]:
myarr.shape

(4, 3)

In [17]:
myarr.size

12

In [18]:
myarr.ndim

2

In [19]:
myarr.dtype

dtype('int64')

In [20]:
myarr=np.array([[1,2,3],[2,3,4],[5,6,7],[4,6,4]],dtype='float64')

In [21]:
myarr

array([[1., 2., 3.],
       [2., 3., 4.],
       [5., 6., 7.],
       [4., 6., 4.]])

In [22]:
myarr=np.array([[1,2,3],[2,3,4],[5,6,7],[4,6,4]])

In [23]:
myarr.shape

(4, 3)

In [25]:
reshaped=myarr.reshape((3,4))

In [26]:
reshaped

array([[1, 2, 3, 2],
       [3, 4, 5, 6],
       [7, 4, 6, 4]])

In [27]:
fllaten=myarr.flatten()


In [28]:
fllaten

array([1, 2, 3, 2, 3, 4, 5, 6, 7, 4, 6, 4])