In [4]:
import numpy as np

In [5]:
 arr2=np.array([[1,2,3],[2,3,4],[5,6,7],[4,6,4]])

In [7]:
flat=arr2.flatten()

In [8]:
flat

array([1, 2, 3, 2, 3, 4, 5, 6, 7, 4, 6, 4])

In [9]:
flat[3]

np.int64(2)

In [10]:
flat[3:6]

array([2, 3, 4])

In [11]:
flat

array([1, 2, 3, 2, 3, 4, 5, 6, 7, 4, 6, 4])

In [12]:
b=flat[2:7].copy()

In [13]:
b[0]=444

In [14]:
flat

array([  1,   2, 444,   2,   3,   4,   5,   6,   7,   4,   6,   4])

In [15]:
b

array([444,   2,   3,   4,   5])

In [18]:
arr=np.array([1,2,3,4,5,6,79,33,55,34,56])

In [19]:
arr[arr>3]

array([ 4,  5,  6, 79, 33, 55, 34, 56])

In [21]:
matrix=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [22]:
matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [24]:
matrix.shape

(3, 3)

In [25]:
np.arange(1,6,2)

array([1, 3, 5])

In [28]:
r=matrix.reshape((3,3))

In [30]:
matrix[matrix>3]

array([4, 4, 5])