In [1]:
import numpy as np
arr=np.array([[1,2,3],
              [3,4,5],
              [5,6,7]])

In [2]:
print(arr)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [3]:
np.sum(arr,axis=0)

array([ 9, 12, 15])

In [6]:
arr[0:2,1:3]

array([[2, 3],
       [4, 5]])

In [11]:
arr3=np.array([[[1,2,3],[3,5,6]],
     [[3,4,5],[6,4,3]]])

In [12]:
print(arr3[0,1,2])

6


In [14]:
print(arr3[:,0,:])

[[1 2 3]
 [3 4 5]]
